### PR TITLE
fix allow options

### PR DESCRIPTION
**Pull request by Ins87**
allow options are not worked, now they are fixed, and got a test for them

### CODE REVIEW

**Comment by Ins87** [comment]
hey guys, will you check this?

**Comment by jacobscarter** [comment]
I will check this out in the next day or two.

Thanks.

**Comment by yzarubin** [comment]
Any word on merging this PR?

**Comment by jacobscarter** [comment]
@yzarubin merged, just need to update npm and bower packages, give me ten mins

**Comment by yzarubin** [comment]
@jacobscarter Great, thanks!

**Pull request merged**
