### PR TITLE
added myFrequency to directive bindings

### PR DESCRIPTION
**Pull request by DmitryEfimenko**
addresses #23
also deleted `angularModule.js` since module is declared twice

### CODE REVIEW

**Comment by jacobscarter** [comment]
@DmitryEfimenko awesome thanks, can you do me a favor and not commit the dist folder, I will build it and release new versions to bower and npm once I merge the source.

Thanks!

**Comment by DmitryEfimenko** [comment]
sure, do you want me to update this PR or just keep this in mind for future PRs?

**Comment by jacobscarter** [comment]
Both please :) If you can update this one and follow that procedure moving forward.

**Comment by jacobscarter** [comment]
I'll also be updating the changelog, readme, and demo so I just do the builds and pushed to bower and npm all in one shot

**Comment by DmitryEfimenko** [comment]
it's done

**Pull request merged**
